
[functions.spotify-login]
enabled = true
verify_jwt = false
import_map = "./functions/spotify-login/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/spotify-login/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/spotify-login/*.html" ]

[functions.spotify-callback]
enabled = true
verify_jwt = false
import_map = "./functions/spotify-callback/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/spotify-callback/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/spotify-callback/*.html" ]

[functions.spotify-search]
enabled = true
verify_jwt = false
import_map = "./functions/spotify-search/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/spotify-search/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/spotify-search/*.html" ]

[functions.spotify-export-played]
enabled = true
verify_jwt = false
import_map = "./functions/spotify-export-played/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/spotify-export-played/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/spotify-export-played/*.html" ]

[functions.stripe-create-payment-intent]
enabled = true
verify_jwt = false
import_map = "./functions/stripe-create-payment-intent/deno.json"
entrypoint = "./functions/stripe-create-payment-intent/index.ts"

[functions.stripe-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/stripe-webhook/deno.json"
entrypoint = "./functions/stripe-webhook/index.ts"

[functions.health-ping]
enabled = true
verify_jwt = false
import_map = "./functions/health-ping/deno.json"
entrypoint = "./functions/health-ping/index.ts"

[functions.stripe-env-check]
enabled = true
verify_jwt = false
import_map = "./functions/stripe-env-check/deno.json"
entrypoint = "./functions/stripe-env-check/index.ts"
